#!/bin/bash

export HF_HOME=/your/path/here
export TRANSFORMERS_CACHE=$HF_HOME/hub
export HF_HUB_CACHE=$HF_HOME/hub
export HF_DATASETS_CACHE=$HF_HOME/datasets
export HF_MODULES_CACHE=$HF_HOME/modules
export HF_TOKEN=your_hf_token_here
export TORCHINDUCTOR_CACHE_DIR=$HF_HOME/torchinductor_cache
export VLLM_CACHE_ROOT=$HF_HOME/vllm_cache
export REDDIT_CLIENT_ID=your_reddit_client_id_here
export REDDIT_CLIENT_SECRET=your_reddit_client_secret_here
